apiVersion: apps/v1 
kind: Deployment
metadata:
  name: eventos
  labels: 
    app: eventos

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: eventos

  template:
    metadata:
      labels:
        app: eventos
    spec:
      containers:
      - name: eventos
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ENV1
        - name: AWS_SECRET_ACCESS_KEY
          value: ENV2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
