apiVersion: v1
kind: Service
metadata:
  name: entrenamiento
  labels:
    app: entrenamiento
spec:
  selector:
    app: entrenamiento

  ports:
<<<<<<< HEAD
    - port: 5002
      targetPort: 5002
=======
    - port: 5000
      targetPort: 5000
>>>>>>> 9098effec7dd0f30314f3866a5bcae0302d6275e

  type: LoadBalancer

