apiVersion: v1
kind: Service
metadata:
  name: entrenamiento
  labels:
    app: entrenamiento
spec:
  selector:
    app: entrenamiento

  ports:
    - port: 5002
      targetPort: 5002

  type: LoadBalancer

