apiVersion: v1
kind: Service
metadata:
  name: eventos
  labels:
    app: eventos
spec:
  type: ClusterIP
  selector:
    app: eventos

  ports:
    - port: 80
      targetPort: 5002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evento-ingress
  
spec:
  ingressClassName: nginx
  rules:
    - host: a1b7563a0858f4f71b48c713a5de8c20-991979942.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /eventos
            pathType: Prefix
            backend:
              service:
                name: eventos
                port:
                  number: 80
